In [ ]:
pip install pymysql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.1 MB/s
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [ ]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

In [ ]:
# db 연결
endpoint = 'dao.c51deksujiip.ap-northeast-2.rds.amazonaws.com'
schema_name = 'dao'
db_connection_str = 'mysql+pymysql://admin:ekfkawnl@{}/{}'.format(endpoint, schema_name )
try :
    db_connection = create_engine(db_connection_str)
    conn = db_connection.connect()
except :
    print('fail to connect db')

In [ ]:
# df_main : maindata
sql = "SELECT * FROM {}".format('MainData')
df_main=pd.read_sql(sql,db_connection)
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   번호                497 non-null    int64
 1   위도                497 non-null    float64
 2   경도                497 non-null    float64
 3   생태통로_유형           497 non-null    int64
 4   차선_수              497 non-null    int64
 5   등산객_이용빈도          497 non-null    int64
 6   생태통로_효율성          497 non-null    int64
 7   이용확인종_수           497 non-null    int64
 8   폭(m)              269 non-null    float64
 9   연장(m)             270 non-null    float64
 10  높이(m)             20 non-null     float64
 11  개방도               21 non-null     float64
 12  경사도               497 non-null    object
 13  주변 로드킬 빈도         497 non-null    int64
 14  산책로까지의 최단 거리(km)  497 non-null    float64
 15  농가까지의 거리(km)      497 non-null    float64
 16  도로 최고제한속도(km/h)   497 non-null    int64
 17  주변 동물종 개수         497 non-null    int64
 18  주변동물 출현빈도         497 non-null    int64
 19  지형기호(2.3km)       497 non-null    object
 20  하천거리(km)          497 non-null    float64
 21  식물군락명             497 non-null    object
 22  등산로까지 최단거리(km)    497 non-null    float64
 23  유도울타리_위도_2.3km    497 non-null    float64
 24  유도울타리_경도_2.3km    497 non-null    float64
 25  유도울타리_연장_m        497 non-null    int64
 26  유도울타리_높이_m        497 non-null    float64
 27  교통량               497 non-null    float64
 28  환경영향평가점수          497 non-null    int64
 29  건물까지거리(km)        497 non-null    float64
dtypes: float64(15), int64(12), object(3)
memory usage: 116.6+ KB

In [ ]:
# df_soil : 경사도 data
df_soil=pd.read_csv('/content/drive/MyDrive/경사도.csv')
df_soil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      497 non-null    int64
 1   위도_십진   497 non-null    float64
 2   경도_십진   497 non-null    float64
 3   생태통로타   497 non-null    int64
 4   차선_수    497 non-null    int64
 5   등산객이용   497 non-null    int64
 6   생태통로효   497 non-null    int64
 7   이용확인종   211 non-null    object
 8   이용확인    497 non-null    int64
 9   면적_m^2  240 non-null    float64
 10  너비_m    240 non-null    float64
 11  길이_m    240 non-null    float64
 12  경사도1    485 non-null    float64
dtypes: float64(6), int64(6), object(1)
memory usage: 50.6+ KB

In [ ]:
# df_soil 열 이름 변경
df_soil.rename(columns={'경사도1':'경사도'}, inplace=True)

# df_soil의 결측치를 0('기타')으로 변경
df_soil['경사도'].fillna(0, inplace = True)

# dtype int형으로 변경
df_soil['경사도']=df_soil['경사도'].astype(int)

In [ ]:
# df_main에 '경사도' 열 추가
df_main['경사도']=df_soil['경사도']
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   번호                497 non-null    int64
 1   위도                497 non-null    float64
 2   경도                497 non-null    float64
 3   생태통로_유형           497 non-null    int64
 4   차선_수              497 non-null    int64
 5   등산객_이용빈도          497 non-null    int64
 6   생태통로_효율성          497 non-null    int64
 7   이용확인종_수           497 non-null    int64
 8   폭(m)              269 non-null    float64
 9   연장(m)             270 non-null    float64
 10  높이(m)             20 non-null     float64
 11  개방도               21 non-null     float64
 12  경사도               497 non-null    int64
 13  주변 로드킬 빈도         497 non-null    int64
 14  산책로까지의 최단 거리(km)  497 non-null    float64
 15  농가까지의 거리(km)      497 non-null    float64
 16  도로 최고제한속도(km/h)   497 non-null    int64
 17  주변 동물종 개수         497 non-null    int64
 18  주변동물 출현빈도         497 non-null    int64
 19  지형기호(2.3km)       497 non-null    object
 20  하천거리(km)          497 non-null    float64
 21  식물군락명             497 non-null    object
 22  등산로까지 최단거리(km)    497 non-null    float64
 23  유도울타리_위도_2.3km    497 non-null    float64
 24  유도울타리_경도_2.3km    497 non-null    float64
 25  유도울타리_연장_m        497 non-null    int64
 26  유도울타리_높이_m        497 non-null    float64
 27  교통량               497 non-null    float64
 28  환경영향평가점수          497 non-null    int64
 29  건물까지거리(km)        497 non-null    float64
dtypes: float64(15), int64(13), object(2)
memory usage: 116.6+ KB

In [ ]:
# df → db
# table_name = 'MainData'
# df_main.to_sql(name=table_name, con=db_connection, if_exists='replace', index=False)